# Generated by Django 5.0.2 on 2024-03-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_alter_profile_email_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/blankpfp.jpg', upload_to='profile_pics/'),
        ),
    ]
