# Generated by Django 5.0.2 on 2024-03-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
